language: java
os:
  - linux
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
script: 
  - "mvn clean install -DskipIntegrationTests=false"
  - "bin/process-docs.sh --dryRun"
  - "mvn process-resources -Djavadoc"